name: CI

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      run: |
        sudo apt update
        sudo apt-get install build-essential libbsd-dev git pkg-config openjdk-8-jdk-headless openjdk-11-jdk-headless
        git clone --recurse-submodules https://github.com/john-tornblom/bdj-sdk
        ln -s /usr/lib/jvm/java-8-openjdk-amd64 bdj-sdk/host/jdk8
        ln -s /usr/lib/jvm/java-11-openjdk-amd64 bdj-sdk/host/jdk11
        make -C bdj-sdk/host/src/makefs_termux
        make -C bdj-sdk/host/src/makefs_termux install DESTDIR=$PWD/bdj-sdk/host
        make -C bdj-sdk/target

    - name: Build
      run: make BDJSDK_HOME=bdj-sdk

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ISO
        path: bdj-ipv6-hen.iso
        if-no-files-found: error

  release:
    needs: build
    permissions:
      contents: write

    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ISO
          path: .

      - name: Create GitHub Release (pre-release)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: true
          files: bdj-ipv6-hen.iso
